"use client";

import { useState, type FormEvent } from "react";

export default function ReviewFeedbackForm({ token }: { token: string }) {
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<{ tone: "success" | "error"; text: string } | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (busy) return; setBusy(true); setMessage(null); try { const form = new FormData(event.currentTarget); const response = await fetch(`/api/review/${token}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ reviewerName: form.get("reviewerName"), reviewerRole: form.get("reviewerRole"), feedback: form.get("feedback"), submissionId: crypto.randomUUID() }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "We could not submit your feedback."); event.currentTarget.reset(); setMessage({ tone: "success", text: "Thank you. Your feedback was shared with the report owner." }); } catch (error) { setMessage({ tone: "error", text: error instanceof Error ? error.message : "We could not submit your feedback. Try again." }); } finally { setBusy(false); } }
  return <section className="reviewer-feedback" aria-labelledby="reviewer-feedback-heading"><h2 id="reviewer-feedback-heading">Leave feedback</h2><p>Your feedback is advice for the owner. Do not include sensitive personal information. You cannot change their CV or report.</p><form onSubmit={submit}><div className="form-fields-row"><label className="form-field" htmlFor="reviewer-name">Display name <span className="optional-label">Optional</span><input id="reviewer-name" name="reviewerName" maxLength={120} autoComplete="name" /></label><label className="form-field" htmlFor="reviewer-role">Role <span className="optional-label">Optional</span><input id="reviewer-role" name="reviewerRole" maxLength={120} autoComplete="organization-title" /></label></div><label className="form-field" htmlFor="reviewer-feedback">Feedback<textarea id="reviewer-feedback" name="feedback" minLength={20} maxLength={4000} rows={7} required /></label><button className="button button-primary" type="submit" disabled={busy}>{busy ? "Submitting feedback…" : "Submit feedback"}</button>{message && <p className={`form-notice ${message.tone === "error" ? "error" : ""}`} role={message.tone === "error" ? "alert" : "status"}>{message.text}</p>}</form></section>;
}
