import { inflateRawSync } from "node:zlib";
import { describe, expect, it, vi } from "vitest";
vi.mock("server-only", () => ({}));
import { createDocx } from "./document";
import { downloadFilename } from "./contract";
import { printHtml, PRINT_CSP } from "./print";

// Independent ZIP reader for generated bytes; no generated document is written to disk.
function entries(bytes: Uint8Array) {
  const buffer = Buffer.from(bytes); const result: Record<string, string> = {};
  const end = buffer.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  let offset = buffer.readUInt32LE(end + 16);
  while (buffer.readUInt32LE(offset) === 0x02014b50) {
    const method = buffer.readUInt16LE(offset + 10); const size = buffer.readUInt32LE(offset + 20);
    const nameLength = buffer.readUInt16LE(offset + 28); const extra = buffer.readUInt16LE(offset + 30); const comment = buffer.readUInt16LE(offset + 32);
    const name = buffer.subarray(offset + 46, offset + 46 + nameLength).toString();
    const local = buffer.readUInt32LE(offset + 42); const start = local + 30 + buffer.readUInt16LE(local + 26) + buffer.readUInt16LE(local + 28);
    const data = buffer.subarray(start, start + size);
    result[name] = (method === 8 ? inflateRawSync(data) : data).toString();
    offset += 46 + nameLength + extra + comment;
  }
  return result;
}
function textFromXml(xml: string) {
  const decode = (text: string) => text.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"').replace(/&apos;/g, "'").replace(/&amp;/g, "&");
  return [...xml.matchAll(/<w:p(?:\s[^>]*)?>[\s\S]*?<\/w:p>/g)].map(([paragraph]) => [...paragraph.matchAll(/<w:t(?:\s[^>]*)?>([\s\S]*?)<\/w:t>|<w:tab\s*\/>/g)].map(([element, text]) => element.startsWith("<w:tab") ? "\t" : decode(text)).join("")).join("\n");
}
describe("immutable CV document formats", () => {
  it("generates editable DOCX with all text, tabs, whitespace, blank and trailing lines preserved", async () => {
    const content = "  Fictional CV — résumé\n\nSkills\nSQL\tpractice & <examples>  \nApproved additional skills\nFictional SQL coursework.\n";
    const archive = entries(await createDocx(content));
    expect(archive["[Content_Types].xml"]).toContain("wordprocessingml.document.main+xml");
    expect(textFromXml(archive["word/document.xml"])).toBe(content);
    expect(archive["word/document.xml"]).toContain('xml:space="preserve"');
    const all = Object.values(archive).join("\n");
    for (const forbidden of ["private-proof.pdf", "storage_path", "reviewer-notes", "access-token", "institutionally verified", "EXE verified"]) expect(all).not.toContain(forbidden);
  });
  it("preserves each logical CRLF/CR line break without creating extra paragraphs", async () => {
    const archive = entries(await createDocx("Fictional first\r\n\r\nFictional last\r"));
    expect(textFromXml(archive["word/document.xml"])).toBe("Fictional first\n\nFictional last\n");
  });
  it("escapes hostile print text, keeps whitespace, and hides controls in print", () => {
    const content = '  Fictional <script>alert("not executed")</script> & CV\n\nClaim\n';
    const html = printHtml(content);
    expect(html).not.toContain(content);
    expect(html).toContain('&lt;script&gt;alert(&quot;not executed&quot;)&lt;/script&gt; &amp; CV\n\nClaim\n');
    expect(html).toContain("Print / Save as PDF");
    expect(html).toContain("EXE does not generate a PDF download");
    expect(html).toContain("@media print"); expect(html).toContain("header{display:none}");
    expect(PRINT_CSP).toContain("script-src 'sha256-"); expect(PRINT_CSP).not.toContain("script-src 'unsafe-inline'");
  });
  it.each(["../../fictional\r\nX-Injected: yes.pdf", 'Fictional"; token="bad.docx', "日本語.pdf", "x".repeat(200) + ".pdf"])("bounds and sanitizes filename %s", (name) => {
    const result = downloadFilename(name, 3, "docx");
    expect(result).toMatch(/^[A-Za-z0-9_-]+-version-3\.docx$/);
    expect(result.length).toBeLessThan(90);
    expect(result).not.toMatch(/[\r\n/\\";]/);
  });
});
