"use client";

import { useEffect, useState } from "react";
import type { OwnerReviewShare, ReviewExpiry } from "@/lib/review-links/types";

const formatDate = (value: string) => new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const expiryLabel = (hours: number) => hours === 24 ? "24 hours" : hours === 168 ? "7 days" : "30 days";

export default function ReviewLinks({ analysisId }: { analysisId: string }) {
  const [shares, setShares] = useState<OwnerReviewShare[] | null>(null);
  const [expiry, setExpiry] = useState<ReviewExpiry>("7d"); const [includeDraft, setIncludeDraft] = useState(false);
  const [notice, setNotice] = useState<{ tone: "success" | "error" | "info"; text: string } | null>(null); const [url, setUrl] = useState(""); const [busy, setBusy] = useState(false);
  const load = async () => { try { const response = await fetch(`/api/analysis/${analysisId}/review-shares`, { cache: "no-store" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); setShares(body.shares); } catch { setNotice({ tone: "error", text: "We could not load your private review links. Try reloading the page." }); setShares([]); } };
  useEffect(() => {
    let current = true;
    fetch(`/api/analysis/${analysisId}/review-shares`, { cache: "no-store" })
      .then(async (response) => ({ response, body: await response.json() }))
      .then(({ response, body }) => {
        if (!current) return;
        if (!response.ok) throw new Error(body.error);
        setShares(body.shares);
      })
      .catch(() => { if (current) { setNotice({ tone: "error", text: "We could not load your private review links. Try reloading the page." }); setShares([]); } });
    return () => { current = false; };
  }, [analysisId]);
  const create = async () => { setBusy(true); setNotice(null); setUrl(""); try { const response = await fetch(`/api/analysis/${analysisId}/review-shares`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ expiry, includeAcceptedDraft: includeDraft }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); const nextUrl = `${window.location.origin}/review/${body.token}`; setUrl(nextUrl); setShares((current) => current ? [body.share, ...current] : [body.share]); setNotice({ tone: "success", text: "Your private review link is ready. Copy it now: it cannot be recovered after you leave or refresh this page." }); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "We could not create your private review link. Try again." }); } finally { setBusy(false); } };
  const revoke = async (shareId: string) => { setBusy(true); setNotice(null); try { const response = await fetch(`/api/analysis/${analysisId}/review-shares`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ shareId }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setNotice({ tone: "success", text: "This private review link was revoked immediately." }); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "We could not revoke that private review link. Try again." }); } finally { setBusy(false); } };
  const copy = async () => { try { await navigator.clipboard.writeText(url); setNotice({ tone: "success", text: "Private review link copied." }); } catch { setNotice({ tone: "info", text: "Copy the link manually from the field." }); } };
  return <section className="review-links-section" aria-labelledby="review-links-heading"><div className="next-steps-heading"><div><p className="eyebrow">PRIVATE REVIEW LINK</p><h2 id="review-links-heading">Ask for feedback you control</h2></div></div><p className="review-links-intro">Anyone with this link can view the selected content until it expires or you revoke it. Share only with someone you trust. The reviewer can give feedback; they cannot change your CV or report.</p><div className="review-link-controls"><label>Link expiry<select value={expiry} onChange={(event) => setExpiry(event.target.value as ReviewExpiry)}><option value="24h">24 hours</option><option value="7d">7 days</option><option value="30d">30 days</option></select></label><label className="review-checkbox"><input type="checkbox" checked={includeDraft} onChange={(event) => setIncludeDraft(event.target.checked)} />Include my accepted CV draft</label><p>Only an explicitly accepted draft can be included. An unaccepted or edited draft stays private.</p><button className="button button-primary" type="button" onClick={() => void create()} disabled={busy}>{busy ? "Creating link…" : "Create private review link"}</button></div>{notice && <p className={`form-notice ${notice.tone === "error" ? "error" : notice.tone === "info" ? "info" : ""}`} role={notice.tone === "error" ? "alert" : "status"}>{notice.text}</p>}{url && <div className="review-url"><label htmlFor="review-url">Copy your new private review URL</label><input id="review-url" readOnly value={url} /><button type="button" className="button button-secondary" onClick={() => void copy()}>Copy link</button></div>}<div className="review-share-list"><h3>Your review links</h3>{shares === null ? <p>Loading your private review links…</p> : !shares.length ? <p>No review links yet. Create one only when you are ready to share this selected report.</p> : shares.map((share) => <article className="review-share-card" key={share.id}><div><strong>{share.state === "active" ? "Active link" : share.state === "expired" ? "Expired link" : "Revoked link"}</strong><p>Created {formatDate(share.createdAt)} · Selected expiry {expiryLabel(share.expiryHours)} · Expires {formatDate(share.expiresAt)} · {share.includesAcceptedDraft ? "Accepted draft included" : "Report only"}</p></div>{share.state === "active" && <button className="text-button danger" type="button" disabled={busy} onClick={() => void revoke(share.id)}>Revoke link</button>}<div className="review-feedback"><strong>{share.feedback.length} feedback {share.feedback.length === 1 ? "entry" : "entries"}</strong>{share.feedback.length ? share.feedback.map((item) => <article key={item.id}><p><strong>{item.reviewerName ?? "Anonymous reviewer"}</strong>{item.reviewerRole ? ` · ${item.reviewerRole}` : ""}</p><p>{item.feedback}</p><small>{formatDate(item.createdAt)}</small></article>) : <p>No feedback yet. Feedback is advice, not verification.</p>}</div></article>)}</div></section>;
}
